// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type GenerateIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateIdRequest) Reset()         { *m = GenerateIdRequest{} }
func (m *GenerateIdRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateIdRequest) ProtoMessage()    {}
func (*GenerateIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *GenerateIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateIdRequest.Unmarshal(m, b)
}
func (m *GenerateIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateIdRequest.Marshal(b, m, deterministic)
}
func (m *GenerateIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateIdRequest.Merge(m, src)
}
func (m *GenerateIdRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateIdRequest.Size(m)
}
func (m *GenerateIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateIdRequest proto.InternalMessageInfo

type GenerateIdResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateIdResponse) Reset()         { *m = GenerateIdResponse{} }
func (m *GenerateIdResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateIdResponse) ProtoMessage()    {}
func (*GenerateIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *GenerateIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateIdResponse.Unmarshal(m, b)
}
func (m *GenerateIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateIdResponse.Marshal(b, m, deterministic)
}
func (m *GenerateIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateIdResponse.Merge(m, src)
}
func (m *GenerateIdResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateIdResponse.Size(m)
}
func (m *GenerateIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateIdResponse proto.InternalMessageInfo

func (m *GenerateIdResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CaptchaRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptchaRequest) Reset()         { *m = CaptchaRequest{} }
func (m *CaptchaRequest) String() string { return proto.CompactTextString(m) }
func (*CaptchaRequest) ProtoMessage()    {}
func (*CaptchaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *CaptchaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaRequest.Unmarshal(m, b)
}
func (m *CaptchaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaRequest.Marshal(b, m, deterministic)
}
func (m *CaptchaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaRequest.Merge(m, src)
}
func (m *CaptchaRequest) XXX_Size() int {
	return xxx_messageInfo_CaptchaRequest.Size(m)
}
func (m *CaptchaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaRequest proto.InternalMessageInfo

func (m *CaptchaRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CaptchaResponse struct {
	Pix                  []byte                 `protobuf:"bytes,1,opt,name=Pix,proto3" json:"Pix,omitempty"`
	Stride               int64                  `protobuf:"varint,2,opt,name=Stride,proto3" json:"Stride,omitempty"`
	Min                  *CaptchaResponse_Point `protobuf:"bytes,3,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *CaptchaResponse_Point `protobuf:"bytes,4,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CaptchaResponse) Reset()         { *m = CaptchaResponse{} }
func (m *CaptchaResponse) String() string { return proto.CompactTextString(m) }
func (*CaptchaResponse) ProtoMessage()    {}
func (*CaptchaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *CaptchaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaResponse.Unmarshal(m, b)
}
func (m *CaptchaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaResponse.Marshal(b, m, deterministic)
}
func (m *CaptchaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaResponse.Merge(m, src)
}
func (m *CaptchaResponse) XXX_Size() int {
	return xxx_messageInfo_CaptchaResponse.Size(m)
}
func (m *CaptchaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaResponse proto.InternalMessageInfo

func (m *CaptchaResponse) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *CaptchaResponse) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *CaptchaResponse) GetMin() *CaptchaResponse_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *CaptchaResponse) GetMax() *CaptchaResponse_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type CaptchaResponse_Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptchaResponse_Point) Reset()         { *m = CaptchaResponse_Point{} }
func (m *CaptchaResponse_Point) String() string { return proto.CompactTextString(m) }
func (*CaptchaResponse_Point) ProtoMessage()    {}
func (*CaptchaResponse_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4, 0}
}

func (m *CaptchaResponse_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaResponse_Point.Unmarshal(m, b)
}
func (m *CaptchaResponse_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaResponse_Point.Marshal(b, m, deterministic)
}
func (m *CaptchaResponse_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaResponse_Point.Merge(m, src)
}
func (m *CaptchaResponse_Point) XXX_Size() int {
	return xxx_messageInfo_CaptchaResponse_Point.Size(m)
}
func (m *CaptchaResponse_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaResponse_Point.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaResponse_Point proto.InternalMessageInfo

func (m *CaptchaResponse_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CaptchaResponse_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type SmsCaptchaRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Captcha              string   `protobuf:"bytes,3,opt,name=Captcha,proto3" json:"Captcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsCaptchaRequest) Reset()         { *m = SmsCaptchaRequest{} }
func (m *SmsCaptchaRequest) String() string { return proto.CompactTextString(m) }
func (*SmsCaptchaRequest) ProtoMessage()    {}
func (*SmsCaptchaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{5}
}

func (m *SmsCaptchaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsCaptchaRequest.Unmarshal(m, b)
}
func (m *SmsCaptchaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsCaptchaRequest.Marshal(b, m, deterministic)
}
func (m *SmsCaptchaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsCaptchaRequest.Merge(m, src)
}
func (m *SmsCaptchaRequest) XXX_Size() int {
	return xxx_messageInfo_SmsCaptchaRequest.Size(m)
}
func (m *SmsCaptchaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsCaptchaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsCaptchaRequest proto.InternalMessageInfo

func (m *SmsCaptchaRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SmsCaptchaRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SmsCaptchaRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type SmsCaptchaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsCaptchaResponse) Reset()         { *m = SmsCaptchaResponse{} }
func (m *SmsCaptchaResponse) String() string { return proto.CompactTextString(m) }
func (*SmsCaptchaResponse) ProtoMessage()    {}
func (*SmsCaptchaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{6}
}

func (m *SmsCaptchaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsCaptchaResponse.Unmarshal(m, b)
}
func (m *SmsCaptchaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsCaptchaResponse.Marshal(b, m, deterministic)
}
func (m *SmsCaptchaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsCaptchaResponse.Merge(m, src)
}
func (m *SmsCaptchaResponse) XXX_Size() int {
	return xxx_messageInfo_SmsCaptchaResponse.Size(m)
}
func (m *SmsCaptchaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsCaptchaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmsCaptchaResponse proto.InternalMessageInfo

type RegisterRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	SmsCaptcha           string   `protobuf:"bytes,3,opt,name=SmsCaptcha,proto3" json:"SmsCaptcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{7}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegisterRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterRequest) GetSmsCaptcha() string {
	if m != nil {
		return m.SmsCaptcha
	}
	return ""
}

type RegisterResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	PublicKey            string   `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	PrivateKey           string   `protobuf:"bytes,4,opt,name=PrivateKey,proto3" json:"PrivateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{8}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegisterResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterResponse) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *RegisterResponse) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type AddNewKeyRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	SmsCaptcha           string   `protobuf:"bytes,2,opt,name=SmsCaptcha,proto3" json:"SmsCaptcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNewKeyRequest) Reset()         { *m = AddNewKeyRequest{} }
func (m *AddNewKeyRequest) String() string { return proto.CompactTextString(m) }
func (*AddNewKeyRequest) ProtoMessage()    {}
func (*AddNewKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{9}
}

func (m *AddNewKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNewKeyRequest.Unmarshal(m, b)
}
func (m *AddNewKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNewKeyRequest.Marshal(b, m, deterministic)
}
func (m *AddNewKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNewKeyRequest.Merge(m, src)
}
func (m *AddNewKeyRequest) XXX_Size() int {
	return xxx_messageInfo_AddNewKeyRequest.Size(m)
}
func (m *AddNewKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNewKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNewKeyRequest proto.InternalMessageInfo

func (m *AddNewKeyRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AddNewKeyRequest) GetSmsCaptcha() string {
	if m != nil {
		return m.SmsCaptcha
	}
	return ""
}

type AddNewKeyResponse struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	PrivateKey           string   `protobuf:"bytes,3,opt,name=PrivateKey,proto3" json:"PrivateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNewKeyResponse) Reset()         { *m = AddNewKeyResponse{} }
func (m *AddNewKeyResponse) String() string { return proto.CompactTextString(m) }
func (*AddNewKeyResponse) ProtoMessage()    {}
func (*AddNewKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{10}
}

func (m *AddNewKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNewKeyResponse.Unmarshal(m, b)
}
func (m *AddNewKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNewKeyResponse.Marshal(b, m, deterministic)
}
func (m *AddNewKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNewKeyResponse.Merge(m, src)
}
func (m *AddNewKeyResponse) XXX_Size() int {
	return xxx_messageInfo_AddNewKeyResponse.Size(m)
}
func (m *AddNewKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNewKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNewKeyResponse proto.InternalMessageInfo

func (m *AddNewKeyResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AddNewKeyResponse) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *AddNewKeyResponse) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type LoginRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{11}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type LoginResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{12}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LogoutRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{13}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{14}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type GetInfoRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{15}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type GetInfoResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{16}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AvatarRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileSize             int64    `protobuf:"varint,4,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarRequest) Reset()         { *m = AvatarRequest{} }
func (m *AvatarRequest) String() string { return proto.CompactTextString(m) }
func (*AvatarRequest) ProtoMessage()    {}
func (*AvatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{17}
}

func (m *AvatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarRequest.Unmarshal(m, b)
}
func (m *AvatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarRequest.Marshal(b, m, deterministic)
}
func (m *AvatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarRequest.Merge(m, src)
}
func (m *AvatarRequest) XXX_Size() int {
	return xxx_messageInfo_AvatarRequest.Size(m)
}
func (m *AvatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarRequest proto.InternalMessageInfo

func (m *AvatarRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *AvatarRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AvatarRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *AvatarRequest) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type AvatarResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarResponse) Reset()         { *m = AvatarResponse{} }
func (m *AvatarResponse) String() string { return proto.CompactTextString(m) }
func (*AvatarResponse) ProtoMessage()    {}
func (*AvatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{18}
}

func (m *AvatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarResponse.Unmarshal(m, b)
}
func (m *AvatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarResponse.Marshal(b, m, deterministic)
}
func (m *AvatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarResponse.Merge(m, src)
}
func (m *AvatarResponse) XXX_Size() int {
	return xxx_messageInfo_AvatarResponse.Size(m)
}
func (m *AvatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarResponse proto.InternalMessageInfo

type RenameRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	NewName              string   `protobuf:"bytes,2,opt,name=NewName,proto3" json:"NewName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameRequest) Reset()         { *m = RenameRequest{} }
func (m *RenameRequest) String() string { return proto.CompactTextString(m) }
func (*RenameRequest) ProtoMessage()    {}
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{19}
}

func (m *RenameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameRequest.Unmarshal(m, b)
}
func (m *RenameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameRequest.Marshal(b, m, deterministic)
}
func (m *RenameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameRequest.Merge(m, src)
}
func (m *RenameRequest) XXX_Size() int {
	return xxx_messageInfo_RenameRequest.Size(m)
}
func (m *RenameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenameRequest proto.InternalMessageInfo

func (m *RenameRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *RenameRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type RenameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameResponse) Reset()         { *m = RenameResponse{} }
func (m *RenameResponse) String() string { return proto.CompactTextString(m) }
func (*RenameResponse) ProtoMessage()    {}
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{20}
}

func (m *RenameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameResponse.Unmarshal(m, b)
}
func (m *RenameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameResponse.Marshal(b, m, deterministic)
}
func (m *RenameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameResponse.Merge(m, src)
}
func (m *RenameResponse) XXX_Size() int {
	return xxx_messageInfo_RenameResponse.Size(m)
}
func (m *RenameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenameResponse proto.InternalMessageInfo

type AuthRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	RealName             string   `protobuf:"bytes,2,opt,name=RealName,proto3" json:"RealName,omitempty"`
	IdCard               string   `protobuf:"bytes,3,opt,name=IdCard,proto3" json:"IdCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{21}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *AuthRequest) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *AuthRequest) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

type AuthResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{22}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

type GetKeysRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeysRequest) Reset()         { *m = GetKeysRequest{} }
func (m *GetKeysRequest) String() string { return proto.CompactTextString(m) }
func (*GetKeysRequest) ProtoMessage()    {}
func (*GetKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{23}
}

func (m *GetKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeysRequest.Unmarshal(m, b)
}
func (m *GetKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeysRequest.Marshal(b, m, deterministic)
}
func (m *GetKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeysRequest.Merge(m, src)
}
func (m *GetKeysRequest) XXX_Size() int {
	return xxx_messageInfo_GetKeysRequest.Size(m)
}
func (m *GetKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeysRequest proto.InternalMessageInfo

func (m *GetKeysRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type GetKeysResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeysResponse) Reset()         { *m = GetKeysResponse{} }
func (m *GetKeysResponse) String() string { return proto.CompactTextString(m) }
func (*GetKeysResponse) ProtoMessage()    {}
func (*GetKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{24}
}

func (m *GetKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeysResponse.Unmarshal(m, b)
}
func (m *GetKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeysResponse.Marshal(b, m, deterministic)
}
func (m *GetKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeysResponse.Merge(m, src)
}
func (m *GetKeysResponse) XXX_Size() int {
	return xxx_messageInfo_GetKeysResponse.Size(m)
}
func (m *GetKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeysResponse proto.InternalMessageInfo

func (m *GetKeysResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DelKeyRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelKeyRequest) Reset()         { *m = DelKeyRequest{} }
func (m *DelKeyRequest) String() string { return proto.CompactTextString(m) }
func (*DelKeyRequest) ProtoMessage()    {}
func (*DelKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{25}
}

func (m *DelKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelKeyRequest.Unmarshal(m, b)
}
func (m *DelKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelKeyRequest.Marshal(b, m, deterministic)
}
func (m *DelKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelKeyRequest.Merge(m, src)
}
func (m *DelKeyRequest) XXX_Size() int {
	return xxx_messageInfo_DelKeyRequest.Size(m)
}
func (m *DelKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelKeyRequest proto.InternalMessageInfo

func (m *DelKeyRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *DelKeyRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type DelKeyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelKeyResponse) Reset()         { *m = DelKeyResponse{} }
func (m *DelKeyResponse) String() string { return proto.CompactTextString(m) }
func (*DelKeyResponse) ProtoMessage()    {}
func (*DelKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{26}
}

func (m *DelKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelKeyResponse.Unmarshal(m, b)
}
func (m *DelKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelKeyResponse.Marshal(b, m, deterministic)
}
func (m *DelKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelKeyResponse.Merge(m, src)
}
func (m *DelKeyResponse) XXX_Size() int {
	return xxx_messageInfo_DelKeyResponse.Size(m)
}
func (m *DelKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelKeyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.user.Message")
	proto.RegisterType((*GenerateIdRequest)(nil), "go.micro.srv.user.GenerateIdRequest")
	proto.RegisterType((*GenerateIdResponse)(nil), "go.micro.srv.user.GenerateIdResponse")
	proto.RegisterType((*CaptchaRequest)(nil), "go.micro.srv.user.CaptchaRequest")
	proto.RegisterType((*CaptchaResponse)(nil), "go.micro.srv.user.CaptchaResponse")
	proto.RegisterType((*CaptchaResponse_Point)(nil), "go.micro.srv.user.CaptchaResponse.Point")
	proto.RegisterType((*SmsCaptchaRequest)(nil), "go.micro.srv.user.SmsCaptchaRequest")
	proto.RegisterType((*SmsCaptchaResponse)(nil), "go.micro.srv.user.SmsCaptchaResponse")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.srv.user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.srv.user.RegisterResponse")
	proto.RegisterType((*AddNewKeyRequest)(nil), "go.micro.srv.user.AddNewKeyRequest")
	proto.RegisterType((*AddNewKeyResponse)(nil), "go.micro.srv.user.AddNewKeyResponse")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.srv.user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.srv.user.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "go.micro.srv.user.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "go.micro.srv.user.LogoutResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "go.micro.srv.user.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "go.micro.srv.user.GetInfoResponse")
	proto.RegisterType((*AvatarRequest)(nil), "go.micro.srv.user.AvatarRequest")
	proto.RegisterType((*AvatarResponse)(nil), "go.micro.srv.user.AvatarResponse")
	proto.RegisterType((*RenameRequest)(nil), "go.micro.srv.user.RenameRequest")
	proto.RegisterType((*RenameResponse)(nil), "go.micro.srv.user.RenameResponse")
	proto.RegisterType((*AuthRequest)(nil), "go.micro.srv.user.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "go.micro.srv.user.AuthResponse")
	proto.RegisterType((*GetKeysRequest)(nil), "go.micro.srv.user.GetKeysRequest")
	proto.RegisterType((*GetKeysResponse)(nil), "go.micro.srv.user.GetKeysResponse")
	proto.RegisterType((*DelKeyRequest)(nil), "go.micro.srv.user.DelKeyRequest")
	proto.RegisterType((*DelKeyResponse)(nil), "go.micro.srv.user.DelKeyResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 810 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x96, 0xdf, 0x4f, 0xe2, 0x58,
	0x14, 0xc7, 0x29, 0x45, 0x91, 0x23, 0x20, 0xdc, 0xdd, 0x6c, 0x48, 0x35, 0x8a, 0x57, 0xdd, 0xf0,
	0xb0, 0xdb, 0x4d, 0xdc, 0xb7, 0x7d, 0x33, 0xba, 0x6b, 0x58, 0xd4, 0x21, 0x25, 0x26, 0x9a, 0xc9,
	0x64, 0x72, 0x95, 0x33, 0xd8, 0x04, 0x5a, 0xa6, 0x2d, 0x0a, 0xf3, 0x34, 0xff, 0xe0, 0xbc, 0xcf,
	0x9f, 0x33, 0xb9, 0xbd, 0xb7, 0x3f, 0x80, 0x4b, 0xc5, 0x79, 0xa2, 0xe7, 0xf6, 0xdc, 0xef, 0xf9,
	0x9e, 0xdb, 0xd3, 0x4f, 0x81, 0xdd, 0xb1, 0xe7, 0x06, 0xee, 0x5f, 0x38, 0x65, 0xa3, 0xf1, 0x10,
	0xa3, 0x5f, 0x33, 0x5c, 0x25, 0xf5, 0x81, 0x6b, 0x8e, 0xec, 0x47, 0xcf, 0x35, 0x7d, 0xef, 0xd9,
	0x9c, 0xf8, 0xe8, 0xd1, 0x5d, 0x28, 0x5e, 0xa3, 0xef, 0xb3, 0x01, 0x92, 0x1a, 0xe8, 0x3e, 0x9b,
	0x35, 0xb4, 0xa6, 0xd6, 0x2a, 0x59, 0xfc, 0x92, 0xfe, 0x02, 0xf5, 0x4b, 0x74, 0xd0, 0x63, 0x01,
	0xb6, 0xfb, 0x16, 0x7e, 0x9e, 0xa0, 0x1f, 0xd0, 0x3f, 0x80, 0xa4, 0x17, 0xfd, 0xb1, 0xeb, 0xf8,
	0x48, 0x7e, 0x83, 0xcd, 0x5b, 0x1f, 0xbd, 0x76, 0x5f, 0xee, 0x97, 0x11, 0x6d, 0x41, 0xf5, 0x9c,
	0x8d, 0x83, 0xc7, 0x27, 0x26, 0xf7, 0xaf, 0xcc, 0xfc, 0xae, 0xc1, 0x4e, 0x9c, 0x2a, 0x55, 0x6b,
	0xa0, 0x77, 0xed, 0x69, 0x98, 0x58, 0xb6, 0xf8, 0x25, 0xdf, 0xdd, 0x0b, 0x3c, 0xbb, 0x8f, 0x8d,
	0x7c, 0x53, 0x6b, 0xe9, 0x96, 0x8c, 0xc8, 0x3f, 0xa0, 0x5f, 0xdb, 0x4e, 0x43, 0x6f, 0x6a, 0xad,
	0xed, 0xd3, 0x96, 0xb9, 0xd4, 0xa8, 0xb9, 0x20, 0x6d, 0x76, 0x5d, 0xdb, 0x09, 0x2c, 0xbe, 0x29,
	0xdc, 0xcb, 0xa6, 0x8d, 0xc2, 0x9b, 0xf7, 0xb2, 0xa9, 0x71, 0x04, 0x1b, 0x61, 0x44, 0xca, 0xa0,
	0xdd, 0x85, 0x46, 0x75, 0x4b, 0xbb, 0xe3, 0xd1, 0xbd, 0x74, 0xa8, 0xdd, 0xd3, 0x0f, 0x50, 0xef,
	0x8d, 0xfc, 0xf5, 0xce, 0x81, 0xaf, 0x5f, 0xbb, 0x0f, 0xf6, 0x50, 0x74, 0x58, 0xb2, 0x64, 0x44,
	0x1a, 0x50, 0x94, 0x0a, 0x61, 0x97, 0x25, 0x2b, 0x0a, 0xe9, 0xaf, 0x40, 0xd2, 0xf2, 0xc2, 0x24,
	0x65, 0xb0, 0x63, 0xe1, 0xc0, 0xf6, 0x03, 0xf4, 0x7e, 0xb6, 0xe4, 0x3e, 0x40, 0x22, 0x2c, 0xab,
	0xa6, 0x56, 0xe8, 0x57, 0x0d, 0x6a, 0x49, 0x8d, 0xec, 0x49, 0x58, 0x59, 0x64, 0x0f, 0x4a, 0xdd,
	0xc9, 0xc3, 0xd0, 0x7e, 0xec, 0xe0, 0x4c, 0xd6, 0x48, 0x16, 0xb8, 0x85, 0xae, 0x67, 0x3f, 0xb3,
	0x00, 0xf9, 0xed, 0x82, 0xb0, 0x90, 0xac, 0xd0, 0xff, 0xa1, 0x76, 0xd6, 0xef, 0xdf, 0xe0, 0x4b,
	0x07, 0x67, 0xa9, 0x36, 0x65, 0x25, 0x2d, 0xa3, 0x9d, 0xfc, 0x52, 0x3b, 0x36, 0xd4, 0x53, 0x5a,
	0x49, 0x3b, 0x4a, 0xb1, 0x39, 0xdb, 0xf9, 0x6c, 0xdb, 0xfa, 0x92, 0xed, 0xdf, 0xa1, 0x7c, 0xe5,
	0x0e, 0x6c, 0xe7, 0x15, 0xcb, 0xf4, 0x4f, 0xa8, 0xc8, 0x3c, 0x69, 0x67, 0x0f, 0x4a, 0x3d, 0xf4,
	0x7d, 0xdb, 0x75, 0xe2, 0x03, 0x4e, 0x16, 0x64, 0xba, 0x3b, 0x09, 0x22, 0xdd, 0xec, 0xf4, 0x1a,
	0x54, 0xa3, 0x74, 0x39, 0x34, 0x26, 0x54, 0x2f, 0x31, 0x68, 0x3b, 0x9f, 0xdc, 0xf5, 0x14, 0x4e,
	0x60, 0x27, 0xce, 0x97, 0x0e, 0x09, 0x14, 0x2e, 0x58, 0xc0, 0xe4, 0x4b, 0x1b, 0x5e, 0xd3, 0x19,
	0x54, 0xce, 0x9e, 0x59, 0xc0, 0xbc, 0xb5, 0x54, 0x63, 0x89, 0x7c, 0x22, 0x41, 0x0c, 0xd8, 0xfa,
	0xcf, 0x1e, 0xe2, 0x0d, 0x1b, 0xa1, 0x3c, 0xcf, 0x38, 0x8e, 0xee, 0xf5, 0xec, 0x2f, 0x18, 0x8e,
	0x88, 0x6e, 0xc5, 0x31, 0xef, 0x31, 0x2a, 0x2d, 0x7b, 0xbc, 0x84, 0x8a, 0x85, 0x0e, 0x1b, 0xe1,
	0x7a, 0x66, 0x1a, 0x50, 0xbc, 0xc1, 0x97, 0xb0, 0xae, 0x78, 0xcc, 0x51, 0xc8, 0xa5, 0x23, 0x21,
	0x29, 0xfd, 0x11, 0xb6, 0xcf, 0x26, 0xc1, 0xd3, 0x7a, 0xc2, 0x06, 0x6c, 0x59, 0xc8, 0x86, 0x29,
	0xe5, 0x38, 0xe6, 0xf3, 0xd0, 0xee, 0x9f, 0x33, 0xaf, 0x2f, 0x7b, 0x95, 0x11, 0xad, 0x42, 0x59,
	0x14, 0x98, 0x7b, 0x5e, 0x1d, 0x9c, 0xf9, 0x6f, 0x79, 0x5e, 0x22, 0x3f, 0xe3, 0x79, 0x75, 0xa0,
	0x72, 0x81, 0xc3, 0xd4, 0x2b, 0x95, 0xdd, 0x49, 0xe6, 0xbb, 0xc0, 0x8f, 0x29, 0x12, 0x13, 0x25,
	0x4f, 0xbf, 0x6d, 0x41, 0xf1, 0x5f, 0xf1, 0x65, 0x22, 0xef, 0x01, 0x92, 0xcf, 0x09, 0x39, 0x56,
	0xd0, 0x77, 0xe9, 0x13, 0x64, 0x9c, 0xbc, 0x92, 0x25, 0x0f, 0x27, 0x47, 0xac, 0x98, 0x99, 0xe4,
	0x30, 0x8b, 0xeb, 0x42, 0x96, 0xbe, 0x8e, 0x7e, 0x9a, 0xe3, 0x86, 0x13, 0x66, 0x28, 0x0d, 0x2f,
	0xb1, 0x5e, 0x69, 0x58, 0x81, 0xec, 0x1c, 0xb9, 0xe5, 0x33, 0x21, 0x80, 0x4a, 0x54, 0x76, 0x16,
	0x88, 0x6e, 0x1c, 0x65, 0xe6, 0xc4, 0xb2, 0x77, 0x50, 0x8a, 0xc9, 0x46, 0x54, 0x7b, 0x16, 0x19,
	0x6a, 0x1c, 0x67, 0x27, 0xc5, 0xca, 0x57, 0xb0, 0x11, 0x02, 0x8a, 0x1c, 0x28, 0x36, 0xa4, 0x11,
	0x67, 0x34, 0x57, 0x27, 0xc4, 0x6a, 0xef, 0x60, 0x53, 0x00, 0x89, 0xac, 0xc8, 0x4e, 0xd0, 0x66,
	0x1c, 0x66, 0x64, 0xa4, 0x07, 0x40, 0xf2, 0x49, 0x39, 0x00, 0xf3, 0xac, 0x53, 0x0e, 0xc0, 0x02,
	0xde, 0x84, 0x49, 0x41, 0x14, 0xa5, 0xc9, 0x39, 0xce, 0x29, 0x4d, 0x2e, 0xe0, 0x28, 0x14, 0x14,
	0x1c, 0x51, 0x0a, 0xce, 0xb1, 0x4a, 0x29, 0xb8, 0x00, 0xa1, 0x1c, 0x69, 0x43, 0x81, 0x53, 0x82,
	0xec, 0xab, 0xaa, 0x27, 0x7c, 0x32, 0x0e, 0x56, 0xde, 0x5f, 0x38, 0x40, 0x0e, 0x8c, 0x55, 0x07,
	0x98, 0x82, 0xcf, 0xaa, 0x03, 0x4c, 0xf3, 0x46, 0xf4, 0x2b, 0x80, 0xa0, 0xec, 0x77, 0x0e, 0x3c,
	0xca, 0x7e, 0xe7, 0x69, 0x42, 0x73, 0x0f, 0x9b, 0xe1, 0xdf, 0xdb, 0xbf, 0x7f, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x22, 0x29, 0xf4, 0x89, 0xfd, 0x0a, 0x00, 0x00,
}
